#!/bin/bash
echo "Updating system"
sudo apt-get update -y && \
echo "Installing BloodHound"
sudo apt-get install bloodhound -y && \
echo "Installing pipx"
sudo apt-get install pipx -y && pipx ensurepath && \
echo "Installing Impacket"
python3 -m pipx install impacket && \
pipx install git+https://github.com/fortra/impacket --force && \
echo "Installing Python BloodHound"
pipx install git+https://github.com/dirkjanm/BloodHound.py --force && \
echo "Installing NetExec"
output=$(pipx install git+https://github.com/Pennyw0rth/NetExec --force 2>&1)
if echo "$output" | grep 'pip failed to build package' -A 2 | grep -q 'aardwolf'; then
    echo "Detected 'pip failed to build package: aardwolf' error. Installing dependencies..."
    sudo apt-get install rustup -y
    rustup default stable
    pip install aardwolf --break-system-packages
    pipx install git+https://github.com/Pennyw0rth/NetExec --force && \
    echo "Run sudo neo4j console to finish Bloodhound setup"
else
    echo "$output"
    echo "Installation completed successfully or different error occurred"
    echo "Run sudo neo4j console to finish Bloodhound setup"
fi
